//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GATEPASS_ALLRECORD
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string EmpCode { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Authority { get; set; }
        public string MobileNumber { get; set; }
        public string StatusAprroved { get; set; }
        public string Resion { get; set; }
    }
}
